services:

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_CI_CD: "1"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: real_estate
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  minio_data:
  postgres_data:
