select
    cian_id,
    region,
    municipality,
    rooms,
    flat_type,
    total_area,
    living_area,
    kitchen_area,
    price,
    round(price / nullif(total_area, 0))::bigint as price_per_m2,
    is_new_building,
    is_studio,
    mortgage_allowed,
    nearest_metro,
    nearest_metro_time,
    nearest_metro_walk,
    n_metro,
    floor,
    total_floors,
    ceiling_height,
    year_built,
    renovation,
    residential_complex,
    developer,
    building_type,
    parking,
    seller_user_type,
    seller_is_owner,
    is_penthouse,
    is_apartments,
    room_type,
    photos_count,
    lat,
    lon,
    publication_date,
    days_on_market
from {{ ref('ml_listings_wide') }}
where event_closed = 0
  and total_area between 10 and 400
  and price between 300000 and 2000000000
