-- живой срез cian, один ряд на объявление
-- дробь активных lifecycle-полей держим здесь, полный history отдельно в price_history
CREATE TABLE IF NOT EXISTS listings (
    cian_id            BIGINT PRIMARY KEY,
    url                TEXT NOT NULL,
    price              BIGINT NOT NULL,
    price_per_m2       BIGINT,
    deal_conditions    TEXT,
    region             TEXT,
    municipality       TEXT,
    district           TEXT,
    microdistrict      TEXT,
    street             TEXT,
    house              TEXT,
    lat                REAL,
    lon                REAL,
    metro_stations     JSONB,
    rooms              SMALLINT,
    total_area         REAL,
    living_area        REAL,
    kitchen_area       REAL,
    floor              SMALLINT,
    total_floors       SMALLINT,
    ceiling_height     REAL,
    renovation         TEXT,
    bathrooms          TEXT,
    balcony            TEXT,
    window_view        TEXT,
    is_apartments      BOOLEAN,
    year_built         SMALLINT,
    building_type      TEXT,
    parking            TEXT,
    is_new_building    BOOLEAN,
    developer          TEXT,
    residential_complex TEXT,
    completion_date    TEXT,
    description        TEXT,
    publication_date   TEXT,
    seller_type        TEXT,
    phone_protected    BOOLEAN,
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    first_seen_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    consecutive_misses SMALLINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_listings_active ON listings (is_active) WHERE is_active;
CREATE INDEX IF NOT EXISTS idx_listings_last_seen ON listings (last_seen_at);
