CREATE SCHEMA IF NOT EXISTS raw;

CREATE TABLE IF NOT EXISTS raw.cian_observations (
    obs_id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cian_id          BIGINT NOT NULL,
    scraped_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    run_id           BIGINT,
    payload          JSONB,
    url              TEXT,
    price            BIGINT,
    price_type       TEXT,
    mortgage_allowed BOOLEAN,
    deal_conditions  TEXT,
    price_per_m2     BIGINT,
    region           TEXT,
    municipality     TEXT,
    district         TEXT,
    microdistrict    TEXT,
    street           TEXT,
    house            TEXT,
    lat              REAL,
    lon              REAL,
    metro_stations   JSONB,
    rooms            SMALLINT,
    is_studio        BOOLEAN,
    flat_type        TEXT,
    total_area       REAL,
    living_area      REAL,
    kitchen_area     REAL,
    floor            SMALLINT,
    total_floors     SMALLINT,
    ceiling_height   REAL,
    renovation       TEXT,
    bathrooms        TEXT,
    balcony          TEXT,
    window_view      TEXT,
    parking          TEXT,
    is_apartments    BOOLEAN,
    year_built       SMALLINT,
    building_type    TEXT,
    passenger_lifts  SMALLINT,
    cargo_lifts      SMALLINT,
    is_new_building  BOOLEAN,
    developer        TEXT,
    residential_complex TEXT,
    completion_date  TEXT,
    description      TEXT,
    publication_date TEXT,
    edit_date        TEXT,
    seller_type      TEXT,
    seller_user_type TEXT,
    phone_protected  BOOLEAN,
    photos_count     SMALLINT,
    views_total      INTEGER,
    views_today      INTEGER
);

CREATE INDEX IF NOT EXISTS idx_obs_cian_id ON raw.cian_observations (cian_id, scraped_at DESC);
